version: '3'
services:
  server:
    build: ./server
    container_name: server_con
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=development

  client:
    build: ./client
    container_name: client_con
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development